name: Post Workflow

on:
  repository_dispatch:
    types: [post_analysis]

jobs:
  analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
    
      - name: Verify information
        run: |
          echo "Ejecución del Workflow luego de 'build-deploy.yaml'"
          echo ${{github.event.client_playload}}
